name: Daily Jest Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 10 PM EST
  workflow_dispatch:     # Allows you to manually trigger it

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project (Next.js)
        run: npm run build

      - name: Run Jest tests
        run: npm test -- --ci
