name: Daily Jest Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 10 PM EST
  workflow_dispatch:     # Allows you to manually trigger it

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd coursemix && npm ci

      - name: Build project (Next.js)
        run: cd coursemix && npm run build
        env:
              NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
              NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
              SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
              RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
              NEXT_PUBLIC_GRADE_ENCRYPTION_SECRET: ${{ secrets.NEXT_PUBLIC_GRADE_ENCRYPTION_SECRET }}
              GRADE_ENCRYPTION_SECRET: ${{ secrets.GRADE_ENCRYPTION_SECRET }}

      - name: Run Jest tests
        run: cd coursemix && npm test -- --ci
